version: '3.8'

services:
  authservice:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: authservice
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AuthDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - Jwt__SecretKey=YourSuperSecretKeyForJWT_MustBe32CharactersOrMore!
      - Jwt__Issuer=eUpravaAuthService
      - Jwt__Audience=eUpravaClients
      - Jwt__ExpireMinutes=60
      - Jwt__RefreshTokenExpireDays=7
    depends_on:
      - sqlserver
    networks:
      - euprava-network

  vehicleservice:
    build:
      context: ./VehicleService
      dockerfile: Dockerfile
    container_name: vehicleservice
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=VehicleDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - Services__AuthService=http://authservice:8080
      - Services__NotificationService=http://notificationservice:8080
      - Jwt__SecretKey=YourSuperSecretKeyForJWT_MustBe32CharactersOrMore!
      - Jwt__Issuer=eUpravaAuthService
      - Jwt__Audience=eUpravaClients
    depends_on:
      - sqlserver
      - authservice
      - notificationservice
    networks:
      - euprava-network

  notificationservice:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    container_name: notificationservice
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=NotificationDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - Email__SenderName=eUprava Vehicle Registration
      - Email__SenderEmail=matijasevicicon@gmail.com
      - Email__SmtpHost=sandbox.smtp.mailtrap.io
      - Email__SmtpPort=587
      - Email__Username=ef5dc9dc17e857
      - Email__Password=9f1f8b5c71e2ef
    depends_on:
      - sqlserver
    networks:
      - euprava-network

  vehiclefrontend:
    build:
      context: ./VehicleFrontend
      dockerfile: Dockerfile
    container_name: vehiclefrontend
    ports:
      - "4200:80"
    depends_on:
      - authservice
      - vehicleservice
    networks:
      - euprava-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - euprava-network

networks:
  euprava-network:
    driver: bridge

volumes:
  sqlserver-data:
